<?php
session_start();
require_once('favicon.php');
echo '<center><br><a href="index.php">Home Page</a><br>
<a href="logout.php">Logout</a></center><br><br>';
if (!isset($_SESSION['adminUser']) || !$_SESSION['adminUser']) {
        echo 'Unauthorized user. You must be an admin to access this page.';
        return false;
    }
    else {
//Check if a list has been pasted
if (isset($_POST['btnUpdateKeywords'])){
	require 'update_keywords.php';
	if (insertKeywords()){
	echo "<h1>Success! Inserted everything above into the keywords table.</h1><br>";
	echo '<center><br><a href="index.php">Home Page</a><br>
<a href="logout.php">Logout</a></center><br><br>';
	exit;
	}
	else {
		echo "<h1>Warning, there was an error inserting into the keywords table.</h1>";
		exit;
	}
}
	}
?>


<html>

<head>
    <title>(Admin) Insert into the keywords table in the database</title>
</head>

<body>
    <div class="myform">
    <form action="" method="post" name="frmKeywords" id="frmKeywords">
        <table border="0" align="center" cellpadding="2" cellspacing="2">
            <tr>
                <td><br><br><br><br><br>Click 'Update Keywords' below to insert the pending keywords files into the database. <br><br>The keywords generated by TextRank are in /files/keywords/.<br><br></td>
			</tr>
			<tr>
			<td><input name="btnUpdateKeywords" type="submit" id="btnUpdateKeywords" value="Update Keywords" class="buttons"></td>
			</tr>
        </table>
    </form>
    </div>
	<?php require_once('footer.php'); ?>
</body>

</html>